version: '3.8'
services:
  python:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    container_name: grrg-python
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8000:8000" # FastAPI
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

  api:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    container_name: grrg-node-api
    depends_on:
      - python
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    working_dir: /app/backend-node
    command: ["node", "server.js"]
